parameters:
- name: officialTemplate
  type: boolean
  default: true
- name: poolConfiguration
  type: object
  default:
    name: Azure-Pipelines-1ESPT-ExDShared
- name: stages
  type: stageList
  default: []
- name: serviceTreeId
  type: string
  default: 7bf80b2c-ef84-47f3-bc43-043356dcb9be

resources:
  repositories:
  - repository: OfficePipelineTemplates
    type: git
    name: 1ESPipelineTemplates/OfficePipelineTemplates
    ref: refs/tags/release

extends:
  ${{ if parameters.officialTemplate }}:
    template: /v1/Office.Official.PipelineTemplate.yml@OfficePipelineTemplates
  ${{ else }}:
    template: /v1/Office.Unofficial.PipelineTemplate.yml@OfficePipelineTemplates

  parameters:
    pool:
      ${{ parameters.poolConfiguration }}
    serviceTreeId: ${{ parameters.serviceTreeId }}
    sdl:
      eslint:
        configuration: required
        parser: '@typescript-eslint/parser'
        parserOptions: 'sourceType:module'
        enableExclusions: true
        exclusionPatterns: ""
        customEnvironments: true
        environmentsBrowser: true
        environmentsNode: true
        environmentsCommonJs: false
        environmentsSharedNodeBrowser: false
        environmentsEs6: true
        environmentsEs2017: true
        environmentsEs2020: true
        environmentsWorker: false
        environmentsAmd: false
        environmentsMocha: false
        environmentsJasmine: false
        environmentsJest: false
        environmentsPhantomjs: false
        environmentsProtractor: false
        environmentsQunit: false
        environmentsJquery: false
        environmentsPrototypejs: false
        environmentsShelljs: false
        environmentsMeteor: false
        environmentsMongo: false
        environmentsApplescript: false
        environmentsNashorn: false
        environmentsServiceworker: false
        environmentsAtomtest: false
        environmentsEmbertest: false
        environmentsWebExtensions: false
        environmentsGreasemonkey: false
    stages: ${{ parameters.stages }}
