trigger: none

schedules:
- cron: '0 8 * * *'
  displayName: Daily Build
  branches:
    include:
    - master
  always: true

variables:
- name: System.Debug
  value: true
- name: tags
  value: nonproduction

extends:
  template: templates/WindowsDevCenterVstsExtension-Build-Base.yml